# Generated by Django 5.2.3 on 2025-07-12 03:44

import django.db.models.deletion
import places.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price_aprox',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[places.validators.validate_price_positive]),
        ),
        migrations.AlterField(
            model_name='place',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='visited',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ubication',
            name='link_maps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ubication',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='coment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rating',
            field=models.IntegerField(validators=[places.validators.validate_rating]),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='places.place')),
            ],
        ),
    ]
